config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  resources :users

  root 'static_pages#index'

  get '/jokes' => 'jokes#index'
  get '/jokes/new' => 'jokes#new', as: 'new_joke'
  get '/jokes/:id' => 'jokes#show', as: 'joke'
  patch '/jokes/:id' => 'jokes#update'
  get '/tags/:tag' => 'jokes#index', as: 'tag'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  

      resources :jokes do
        resources :notes
      end
      resources :tags 

end

app/models/joke.rb
class Joke < ActiveRecord::Base
	acts_as_taggable
	belongs_to :user
	has_many :notes

	def average_rating
  		notes.average(:rating).to_f
	end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :joke

  validates :body, presence: true
  validates :user, presence: true
  validates :joke, presence: true
  #validates :rating, numerically: { only_integer: true }
end

app/models/subject.rb
class Subject < ActiveRecord::Base

	belongs_to :joke
	belongs_to :tag

	accepts_nested_attributes_for :joke, :reject_if => :all_blank
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :jokes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||=User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
  	redirect_to '/login' unless current_user
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
before_action :require_user, only: [:index, :show, :new, :edit]
	def index
		if params[:tag]
			@user = User.find(current_user)
			@jokes = @user.jokes.tagged_with(params[:tag]).order("created_at DESC")
			@tag = @jokes.name
		else
			@user = User.find(current_user)
			@jokes = @user.jokes.all.order("created_at DESC")
		end
	end

	def new
		@user = User.find(current_user)
		@joke = Joke.new
	end

	def edit
		@user = User.find(current_user)
		@joke = Joke.find(params[:id])
	end

	def create
		@new_joke = current_user.jokes.new(joke_params)
		if @new_joke.save
			redirect_to joke_path(@new_joke), notice: 'Great new joke you got there!'
		else
			render 'new'
		end
	end

	def show
		@user= User.find(current_user)
		@joke = Joke.find(params[:id])
		@notes = @joke.notes.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
	end

	def update
		@joke = Joke.find(params[:id])
    	respond_to do |format|
     		if @joke.update(joke_params)
        		format.html { redirect_to @joke, notice: 'Great new joke you got there!' }
        		format.json { render :show, status: :ok, location: @joke }
 		  	else
        		format.html { render :edit }
        		format.json { render json: @product.errors, status: :unprocessable_entity }
      		end
      	end
    end

    def destroy
    	@joke = Joke.find(params[:id])
    	@joke.destroy
    	respond_to do |format|
      		format.html { redirect_to jokes_url, notice: 'That joke is outta here!' }
      		format.json { head :no_content }
   	 	end
  	end
	
	private
		def joke_params
			params.require(:joke).permit(:id, :title, :content, :tag_list, :user_id, :tag)
		end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def create
		@joke = Joke.find(params[:joke_id])
		@note = @joke.notes.new(note_params)
		@note.user = current_user
		respond_to do |format|
			if @note.save
				format.html { redirect_to @joke, notice: 'Note saved.'}
				format.json { render :show, satus: :created, location: @joke}
			else
				format.html { redirect_to @joke, alert: 'Sorry, your note was not saved.'}
				format.json { render json: @note.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@note = Note.find(params[:id])
		joke = @note.joke
		@note.destroy
		redirect_to joke
	end

	private
	def note_params
		params.require(:note).permit(:user_id, :body, :rating)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user=User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id]=@user.id
			redirect_to '/'
		else
			redirect_to 'login'
		end
	end

	def destroy
		session[:user_id]=nil
		redirect_to '/'
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	if current_user
  	@user = User.find(current_user)
  	else
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def show
		@user=User.find(params[:id])
	end

	def create
		@user=User.new(user_params)
		if @user.save
			session[:user_id]=@user.id
			redirect_to '/'
		else
			redirect_to '/signup'
		end
	end

	def edit
		@user=User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		respond_to do | format |
			if @user.update(user_params)
				format.html { redirect_to @user, notice: 'Your info was updated!'}
				format.json { render :show, status: :ok, location: @user}
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jokes/_new_note.html.erb
<% if current_user %>
	<%= form_for ([@joke, @joke.notes.build]) do |f| %>
		<p>
			<%= f.label :"Add Some Notes:" %><br>
			<%= f.text_area :body %>
		</p>
		<!--<p>
			<%= f.label :rating %><br>
			<%= f.text_field :rating %>
		</p>-->
		<p>
			<%= f.label :rating, "Laugh-O-Meter" %>
			<div class="rating"></div>
		</p>
			<%= f.submit "Add Notes", class: "btn btn-send"%>
	<% end %>
<% end %>

<div class="joke-notes">
	<% @notes.each do |note| %>
		<div class="row">
			<hr>
			<p><small><em><%= "#{(note.created_at.strftime("%b %-d, %Y"))}" %></em></small>
				<% if current_user %>
					<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, joke_note_path(@joke, note), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</p>	
			<div class="rated" data-score="<%= note.rating %>"></div>
			<p><%= note.body %></p>
		</div>
	<% end %>
</div>

<%= will_paginate @notes %>

app/views/jokes/edit.html.erb
<div class='main'>
  <div class='container'>
    <h1>Edit Your Joke!</h1>

    <%= form_for(@joke) do |f| %>
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :tag_list, "Tags (separated by commas)" %><br>
        <%= f.text_field :tag_list %>
      </div>
      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_area :content %>
      </div>
      <div class="actions">
        <p><%= f.submit "Update Joke", class: "btn btn-send"%></p>
        <p><%= link_to "Cancel", jokes_path, class: "btn btn-cta" %></p>
      </div>
    <% end %>
  </div>
</dvi>

app/views/jokes/index.html.erb
<div class="main">
	<div class="container">
		<% if notice %>
			<p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
		<% end %>
		<h1>My Tags</h1>
		<div id="tag_cloud">
			<% tag_cloud current_user.jokes.tag_counts, %w[s m l] do |tag, css_class| %>
				<%= link_to tag.name, tag_path(tag.name), class: css_class %>
			<% end %>
		</div>
		<div>
			<% if params[:tag] %>
				<h3>Jokes tagged with <em><%= params[:tag] %></em> :</h3>
					<% @jokes.each do |j| %>
					<div class="jokes col-lg-6">
						<h3><a href='<%= joke_path(j) %>'><%= j.title %></a></h3>
						<small><em><%= "#{(j.created_at.strftime("%b %-d, %Y"))}" %></em></small>
						<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, j, method: :delete, data: { confirm: 'Whoa! Do you really want to get rid of this knee-slapper?' } %>
						<p> <div class="rated" data-score="<%= j.average_rating %>"></div> </p>
						<p>
							Tags: <%= raw j.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
						</p>
					</div>
				<% end %>
			<% else %>
				<div class="row col-lg-12">
				<h1 class="row col-lg-6 col-md-6 col-sm-6">My Jokes</h1>
				<%= link_to "New Joke", new_joke_path, class: "row col-lg-6 new_joke btn btn-send" %>
				</div>
				<% @jokes.each do |j| %>
					<div class="jokes col-lg-6">
						<h3><a href='<%= joke_path(j) %>'><%= j.title %></a></h3>
						<small><em><%= "#{(j.created_at.strftime("%b %-d, %Y"))}" %></em></small>
						<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, j, method: :delete, data: { confirm: 'Whoa! Do you really want to get rid of this knee-slapper?' } %>
						<p> <div class="rated" data-score="<%= j.average_rating %>"></div> </p>
						<p>
							Tags: <%= raw j.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
						</p>
					</div>
				<% end %>
			<% end %>
		</div>
		<!--<h1>My Jokes</h1>
		<% @jokes.each do |j| %>
			<div class="jokes col-lg-6">
				<h3><a href='<%= joke_path(j) %>'><%= j.title %></a></h3>
				<small><em><%= "#{(j.created_at.strftime("%b %-d, %Y"))}" %></em></small>
				<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, j, method: :delete, data: { confirm: 'Whoa! Do you really want to get rid of this knee-slapper?' } %>
				<p> <div class="rated" data-score="<%= j.average_rating %>"></div> </p>
				<p>
					Tags: <%= raw j.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
				</p>
			</div>
		<% end %>-->
	</div>
</div>

app/views/jokes/new.html.erb
<div class='main'>
	<div class='container'>
		<h1>New Joke</h1>
		<%= form_for (@joke) do |f| %>
			<div class="field">
				<%= f.label :Title %><br>
				<%= f.text_area :title %>
			</div>
			<div class="field">
				<%= f.label :Joke %><br>
				<%= f.text_area :content %>
			</div>
			<div class="field">
    			<%= f.label :tag_list, "Tags (separated by commas)" %><br>
    			<%= f.text_field :tag_list %>
  			</div>
			<div class="actions">
				<p><%= f.submit "Create", class: 'btn btn-send' %></p>
				<p><%= link_to "CANCEL", jokes_path, class: "btn btn-cta" %></p>
			</div>
		<% end %>
	</div>
</div>

app/views/jokes/show.html.erb
<div class="main">
	<div class="container">
		<% if notice %>
			<p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
		<% end %>
		<h1><%= @joke.title %></h1>
		<p><div class="rated" data-score="<%= @joke.average_rating %>"></div> </p>
		<small><em><%= "#{(@joke.created_at.strftime("%b %-d, %Y"))}" %></em></small>
		<div>
			<p>Tags: <%= raw @joke.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %><p>
		</div>
		<div class="jokes">
			<p><%= @joke.content %></p>
		</div>
		<div class="edit">
			<small><em><strong><%= link_to "Edit", edit_joke_path(@joke), class: "btn btn-send"%></strong></em></small>
			<small><em><strong><%= link_to 'Delete', @joke, method: :delete, data: { confirm: 'Whoa! Do you really want to get rid of this knee-slapper?' }, class: "btn btn-cta" %></strong></em></small>
		</div>
		<div class='add_note'>
			<%= render 'new_note' %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaughTracker</title>
  
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>  
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic|Puritan:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="navbar">
	<div id="user_name">
		<% if current_user %>
        <a href='<%= user_path(@user) %>'><%= current_user.first_name %></a>
      <% else %>
        <a>LaughTracker</a>
      <% end %>
	</div>
    <ul class="nav navbar-nav">
    <% if current_user %>
    	<%= link_to 'Jokes', jokes_path %>
    	<%= link_to 'Create', new_joke_path %>
      <%= link_to 'Home', root_path %>
      <%= link_to "Logout", logout_path, method: "delete" %>
    <% else %>
        <%= link_to "Login", 'login' %></a>
		    <%= link_to "Sign Up", 'signup' %></a>
    <% end %>
    </ul>
</div>
<%= yield %>
	
</body>
</html>

app/views/static_pages/index.html.erb
<div class="header">
	<%= image_tag("homepage.jpg") %>
	<div class="header-caption">
		<h1 class="cap-2">Laugh</h1><h1 class="cap-1">Tracker</h1><br>
		<h2 class="cap-1">Track of your jokes.</h2><h2 class="cap-2">Get  more laughs.</h2>
	</div>
	<div class="container">
		<% if current_user %>
		<% else %>
		<div class="index-buttons">
			<div class="row col-lg-3"><%= link_to "LOGIN", "login", class: "btn btn-send" %>
			</div>
			<div class="row col-lg-3">
			<%= link_to "SIGN UP", "signup", class: "btn btn-cta" %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<div class="container features">
		<div class="feature feature_1 col-sm-4 col-md-4 col-lg-4">
			<h1><span class="glyphicon glyphicon-pencil"></span></h1>
			<p>Write, edit, and save your jokes.</p>
		</div>
		<div class="feature feature_2 col-sm-4 col-md-4 col-lg-4">
			<h1><span class="glyphicon glyphicon-tag"></span></h1>
			<p>Tag jokes and easily search for them by subject.</p>
		</div>
		<div class="feature feature_3 col-sm-4 col-md-4 col-lg-4">
			<h1><span class="glyphicon glyphicon-star"><span class="glyphicon glyphicon-star"><span class="glyphicon glyphicon-star"><span class="glyphicon glyphicon-star-empty"></span><span class="glyphicon glyphicon-star-empty"></span></h1>
			<p>Rate your jokes and track their success over time.</p>
		</div>
</div>
<div class="container endorsements">
		<div class="endorsement endorsement_1 col-sm-4 col-md-4 col-lg-4">
			<div class="photo">
				<img src="http://img.timeinc.net/time/2011/time_100_walkup/louis_ck.jpg" class="img-responsive">
			</div>
			<h1>Louis C.K.</h1>
			<p>"No comedian should be without LaughTracker."</p>
		</div>
		<div class="endorsement endorsement_2 col-sm-4 col-md-4 col-lg-4">
			<div class="photo">
				<img src="http://p.fod4.com/p/channels/zzbuf/profile/s=w1200/o=95/Kvz7cZVTTRWXBNLIRowA_aziz_ansari.jpg" class="img-responsive">
			</div>
			<h1>Aziz Ansari</h1>
			<p>"It's never been easier to improve my jokes."</p>
		</div>
		<div class="endorsement endorsement_3 col-sm-4 col-md-4 col-lg-4">
			<div class="photo">
				<img src="http://www.famousbirthdays.com/headshots/sarah-silverman-1.jpg" class="img-responsive">
			</div>
			<h1>Sarah Silverman</h1>
			<p>"I used to have a million notebooks for my jokes.  Now I just have one app."</p>
		</div>
</div>

app/views/users/edit.html.erb
<div class="main">
	<div class="container">
		<h1>Your Info</h1>
		<%= form_for(@user) do |f| %>
			<div class="field">
				<%= f.label :fist_name %><br>
				<%= f.text_field :first_name %>
			</div>
			<div class="field">
				<%= f.label :last_name %><br>
				<%= f.text_field :last_name %>
			</div>
			<div class="field">
				<%= f.label :email %><br>
				<%= f.text_field :email %>
			</div>
			<div class="field">
				<%= f.label :password %><br>
				<%= f.password_field :password, :placeholder => "Password" %>
			</div>
			<div class="field">
				<%= f.submit "UPDATE", class: "btn btn-send" %>
			</div>
			<%= link_to "CANCEL", user_path, class: 'btn btn-cta' %>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<div class="main">
	<div class="container">
		<h1>Sign Up!</h1>
		<%= form_for(@user) do |f| %>
			<div class="field">
				<%= f.text_field :first_name, :placeholder => "First Name" %>
			</div>
			<div class="field">
				<%= f.text_field :last_name, :placeholder => "Last Name" %>
			</div>
			<div class="field">
				<%= f.text_field :email, :placeholder => "Email" %>
			</div>
			<div class="field">
				<%= f.password_field :password, :placeholder => "Password" %>
			</div>
			<div class="field">
				<%= f.submit "Create an Account", class: "btn-submit" %>
			</div>	
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="main">
	<div class="container">
		<% if notice %>
			<p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
		<% end %>
		<h1> You're Using Laugh Tracker, <%= @user.first_name %>!</h1>
		<p><%= @user.first_name %><br></p>
		<p><%= @user.last_name %><br></p>
		<p><%= @user.email %><br></p>
		<%= link_to "Change Details", edit_user_path, class: 'btn btn-send' %>
	</div>
</div>